Herbstluftwm config now has  - backlight and password binds  - fixed multi-monitor switching  - improved tag creation system in its own script  - theming

diff --git a/dotfiles/.config/herbstluftwm/autostart b/dotfiles/.config/herbstluftwm/autostart
--- a/dotfiles/.config/herbstluftwm/autostart
+++ b/dotfiles/.config/herbstluftwm/autostart
@@ -35,6 +35,16 @@ hc keybind $Mod-m spawn chSink
 hc keybind $Mod-Shift-m spawn chMp
 #hc keybind $Mod-m spawn chMp
 
+# Brightness
+hc keybind XF86MonBrightnessUp spawn chBl +10
+hc keybind XF86MonBrightnessDown spawn chBl -10
+
+# Password Stuff
+hc keybind $Mod-p spawn sh -c 'passmenu'
+hc keybind $Mod-Shift-p spawn sh -c 'ykOath'
+
+hc keybind Mod4-BackSpace spawn sh -c 'powerMenu'
+
 # basic movement in tiling and floating mode
 # focusing clients
 hc keybind $Mod-Left  focus left
@@ -57,7 +67,7 @@ hc keybind $Mod-Shift-k     shift up
 hc keybind $Mod-Shift-l     shift right
 # move between monitors
 hc keybind $Mod-Shift-comma shift_to_monitor -1
-hc keybind $Mod-Shift-period shift_to_monitor 1
+hc keybind $Mod-Shift-period shift_to_monitor +1
 
 # splitting frames
 # create an empty frame at the specified direction
@@ -94,33 +104,36 @@ hc set default_frame_layout max
 #    fi
 #done
 
-# Good Logic
-mon1_names=( 1_{1..9} 1_0 ) # tag names for monitor 1
-mon2_names=( 2_{1..9} 2_0 ) # tag names for monitor 2
-fallback_names=( {1..9} 0 ) # tag names for all other monitors
-tag_keys=( {1..9} 0 )
+## Good Logic
+#mon1_names=( 1_{1..9} 1_0 ) # tag names for monitor 1
+#mon2_names=( 2_{1..9} 2_0 ) # tag names for monitor 2
+#fallback_names=( {1..9} 0 ) # tag names for all other monitors
+#tag_keys=( {1..9} 0 )
+#
+#hc rename default "${mon1_names[0]}" || true
+#for tag in "${mon1_names[@]}" "${mon2_names[@]}" "${fallback_names[@]}" ; do
+#    hc try silent add "$tag"
+#done
+#
+#for i in ${!tag_keys[@]} ; do
+#    key="${tag_keys[$i]}"
+#    # the keybinding works as follows: the or executes the commands separated by
+#    # CASE and stops executing them after the first of those succeeds.
+#    # the first command is: check that we are on monitor 3 and can switch to tag "${mon1_names[$i]}"
+#    # if only one of these two steps fail, try the second one (and so one).
+#    # The setup for two monitors is as follows:
+#    hc keybind "$Mod-$key" \
+#        or CASE and . compare monitors.focus.index = 0 . use "${mon1_names[$i]}" \
+#           CASE and . compare monitors.focus.index = 1 . use "${mon2_names[$i]}" \
+#           CASE use "${fallback_names[$i]}"
+#    hc keybind "$Mod-Shift-$key" \
+#        or CASE and . compare monitors.focus.index = 0 . move "${mon1_names[$i]}" \
+#           CASE and . compare monitors.focus.index = 1 . move "${mon2_names[$i]}" \
+#           CASE move "${fallback_names[$i]}"
+#done
 
-hc rename default "${mon1_names[0]}" || true
-for tag in "${mon1_names[@]}" "${mon2_names[@]}" "${fallback_names[@]}" ; do
-    hc try silent add "$tag"
-done
-
-for i in ${!tag_keys[@]} ; do
-    key="${tag_keys[$i]}"
-    # the keybinding works as follows: the or executes the commands separated by
-    # CASE and stops executing them after the first of those succeeds.
-    # the first command is: check that we are on monitor 3 and can switch to tag "${mon1_names[$i]}"
-    # if only one of these two steps fail, try the second one (and so one).
-    # The setup for two monitors is as follows:
-    hc keybind "$Mod-$key" \
-        or CASE and . compare monitors.focus.index = 0 . use "${mon1_names[$i]}" \
-           CASE and . compare monitors.focus.index = 1 . use "${mon2_names[$i]}" \
-           CASE use "${fallback_names[$i]}"
-    hc keybind "$Mod-Shift-$key" \
-        or CASE and . compare monitors.focus.index = 0 . move "${mon1_names[$i]}" \
-           CASE and . compare monitors.focus.index = 1 . move "${mon2_names[$i]}" \
-           CASE move "${fallback_names[$i]}"
-done
+# Better Logic
+$HOME/.config/herbstluftwm/scripts/manage_mons
 
 # layouting
 hc keybind $Mod-r remove
@@ -163,37 +176,39 @@ hc keybind $Mod-comma cycle_monitor -1
 # theme
 hc attr theme.tiling.reset 1
 hc attr theme.floating.reset 1
-hc set frame_border_active_color '#222222'
-hc set frame_border_normal_color '#101010'
-hc set frame_bg_normal_color '#565656'
-hc set frame_bg_active_color '#345F0C'
-hc set frame_border_width 1
+hc set frame_border_active_color '#5E81AC'
+hc set frame_border_normal_color '#2E3440'
+hc set frame_bg_normal_color '#2E3440'
+hc set frame_bg_active_color '#5E81AC'
+hc set frame_border_width 0
 hc set always_show_frame on
 hc set frame_bg_transparent on
 hc set frame_transparent_width 5
-hc set frame_gap 0
+hc set frame_gap 10
 
+# Title/Borders
 hc attr theme.title_height 13
-hc attr theme.title_font 'Cozette:pixelsize=10'  # example using Xft
+#hc attr theme.title_font 'Cozette:pixelsize=11'  # example using Xft
+hc attr theme.title_font 'Iosevka Ruwey:size=10'
 # hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
 hc attr theme.padding_top 2  # space below the title's baseline (i.e. text depth)
-hc attr theme.active.color '#9fbc00'
-hc attr theme.normal.color '#454545'
+hc attr theme.active.color '#88C0D0'
+hc attr theme.normal.color '#3B4252'
+hc attr theme.normal.title_color '#2E3440' 
 hc attr theme.urgent.color orange
-hc attr theme.inner_width 1
+hc attr theme.inner_width 0
 hc attr theme.inner_color black
 hc attr theme.border_width 3
 hc attr theme.floating.border_width 4
 hc attr theme.floating.outer_width 1
 hc attr theme.floating.outer_color black
-hc attr theme.active.inner_color '#3E4A00'
-hc attr theme.active.outer_color '#3E4A00'
+hc attr theme.active.title_color '#2E3440'
 hc attr theme.background_color '#141414'
 
-hc set window_gap 10
+hc set window_gap 0
 hc set frame_padding 0
 hc set smart_window_surroundings off
-hc set smart_frame_surroundings on
+hc set smart_frame_surroundings off
 hc set mouse_recenter_gap 0
 hc set focus_follows_mouse true
 
@@ -220,7 +235,7 @@ hc unlock
 # do multi monitor setup here, e.g.:
 # hc set_monitors 1280x1024+0+0 1280x1024+1280+0
 # or simply:
-hc detect_monitors
+$HOME/.config/herbstluftwm/scripts/detect_monitors
 
 # find the panel
 #panel=~/.config/herbstluftwm/panel.sh
